version: '2'
services:
  oracle:
    image: container-registry.oracle.com/database/enterprise:12.2.0.1 # 12C
    container_name: oracle
    environment:
      - ORACLE_PWD=top_secret
    ports:
      - 1521:1521
